language: php
php:
    - 5.4
    - 5.5
    - 5.6

sudo: false

install:
  - travis_retry composer update && composer install --no-interaction --prefer-source

script:
    phpunit --bootstrap=./vendor/autoload.php ./tests
